/* 
    Sania Azhar    (z1884677)
    Nikolas Gatov  (z1884744)
    Leo Jaos       (z1911688)
    Olivia Merrell (z1896986)
    Muhammad Naeem (z1906224)
    
    CSCI 466-0001
    Group Project - Karaoke Management System
*/

INSERT INTO Users (Name)
       VALUES
              ('Sania'),
              ('Nikolas'),
              ('Leo'),
              ('Olivia'),
              ('Muhammad'),
              ('Linda'),
              ('Connor'),
              ('Suzy'),
              ('Henry'),
              ('Megan');

INSERT INTO Songs (Title, Artist)
       VALUES
              ('I Want It that Way',  'The Backstreet Boys'),
              ('Dont Stop Believing', 'Journey'),
              ('Señorita', 'Shawn Mendes Feat. Camila Cabello'),
              ('I Wanna Dance with Someone', 'Whitney Houston'),
              ('Bohemian Rhapsody','Queen'),
              ('Wannabe','Spice Girls'),
              ('Party in the U.S.A', 'Miley Cyrus'),
              ('Someone Like You', 'Adele'),
              ('Call Me Maybe', 'Carly Rae Jepsen'),
              ('Bye Bye Bye', 'NSYNC'),
              ('Single Ladies (Put a Ring on it)', 'Beyonce'),
              ('Cry Me a River', 'Justin Timberlake'),
              ('Oh Sherrie', 'Steve Perry'),
              ('Billie Jean', 'Michael Jackson'),
              ('Dancing Queen', 'ABBA'),
              ('Material Girl', 'Madonna'),
              ('Here Comes the Sun', 'The Beatles'),
              ('Dont Go Breaking My Heart', 'Elton John Feat. Kiki Dee'),
              ('Under Pressure', 'Queen Feat. David Bowie'),
              ('Empire State Of Mind', 'Jay Z. Feat. Alicia Keys'),
              ('Stayin Alive', 'The Bee Gees'),
              ('You’ve Lost the Loving Feeling', 'The Righteous Brothers'),
              ('Girl on Fire', 'Alicia Keys'),
              ('Rocket Man', 'Elton John'),
              ('Havana', 'Camila Cabello'),
              ('The Story of My Life', 'One Direction'),
              ('...Baby One More Time', 'Britney Spears'),
              ('Careless Whisper',  'George Michael'),
              ('Wake Me Up Before You Go-Go', 'Wham!'),
              ('Baby', 'Justin Bieber Feat. Ludacris');

INSERT INTO Contributor (Name)
       VALUES
              ('Max Martin'),
              ('Nick Carter'),
              ('Kevin Richardson'),
              ('Brian Littrell'),
              ('AJ McLean'),
              ('Steve Perry'),
              ('Neal Schon'),
              ('Ross Valory'),
              ('George Tickner'),
              ('Prairie Prince'),
              ('Camila Cabello'),
              ('Shawn Mendes'),
              ('Whitney Houston'),
              ('George Merrill'),
              ('Freddie Mercury'),
              ('Brian May'),
              ('Roger Taylor'),
              ('John Deacon'),
              ('Mel B'),
              ('Mel C'),
              ('Emma Bunton'),
              ('Geri Halliwell'),
              ('Victoria Beckham'),
              ('Miley Cyrus'),
              ('Jessie J'),
              ('Adele'),
              ('Carly Rae Jepsen'),
              ('Justin Timberlake'),
              ('JC Chasez'),
              ('Chris Kirkpatrick'),
              ('Joey Fatone'),
              ('Lance Bass'),
              ('Beyonce'),
              ('Michael Jackson'),
              ('Agnetha Fältskog'),
              ('Björn Ulvaeus'),
              ('Benny Andersson'),
              ('Anni-Frid Lyngstad'),
              ('Madonna'),
              ('Nile Rodgers'),
              ('John Lennon'),
              ('Paul McCartney'),
              ('George Harrison'),
              ('Ringo Starr'),
              ('Elton John'),
              ('Kiki Dee'),
              ('Gus Dudgeon'),
              ('David Bowie'),
              ('Jay Z'),
              ('Alicia Keys'),
              ('Al Shux'),
              ('Barry Gibb'),
              ('Robin Gibb'),
              ('Maurice Gibb'),
              ('Bill Medley'),
              ('Bobby Hatfield'),  
              ('Phil Spector'),
              ('Britney Spears'),
              ('Harry Styles'),
              ('Niall Horan'),
              ('Zayn Malik'),
              ('Liam Payne'),
              ('Louis Tomlinson'),
              ('George Michael'),
              ('Andrew Ridgeley'),
              ('Justin Bieber'),
              ('Ludacris');

INSERT INTO Kfiles (Version, SID)
       VALUES
              ('Solo', 1),
              ('Duet', 1),
              ('Solo', 2),
              ('Duet', 2),
              ('Solo', 3),
              ('Duet', 3),
              ('Solo', 4),
              ('Solo', 5),
              ('Duet', 5),
              ('Solo', 6),
              ('Duet', 6),
              ('Solo', 7),
              ('Solo', 8),
              ('Solo', 9),
              ('Duet', 9),
              ('Solo', 10),
              ('Duet', 10),
              ('Solo', 11),
              ('Solo', 12),
              ('Solo', 13),
              ('Solo', 14),
              ('Solo', 15),
              ('Duet', 15),
              ('Solo', 16),
              ('Solo', 17),
              ('Duet', 17),
              ('Solo', 18),
              ('Duet', 18),
              ('Solo', 19),
              ('Duet', 19),
              ('Solo', 20),
              ('Duet', 20),
              ('Solo', 21),
              ('Duet', 21),
              ('Solo', 22),
              ('Duet', 22),
              ('Solo', 23),
              ('Solo', 24),
              ('Solo', 25),
              ('Solo', 26),
              ('Duet', 26),
              ('Solo', 27),
              ('Solo', 28),
              ('Duet', 28),
              ('Solo', 29),
              ('Duet', 29),
              ('Solo', 30);

INSERT INTO Contribution (SID, CID, Role)
       VALUES           
              (1, 1, 'Writer/Producer'),
              (1, 2, 'Vocals' ),  
              (1, 3, 'Vocals' ),
              (1, 4, 'Vocals' ),
              (1, 5, 'Vocals' ),
              (2, 6, 'Vocals/Writer'),
              (2, 7, 'Guitarist'),
              (2, 8, 'Bassist'),
              (2, 9, 'Guitarist'),
              (2, 10, 'Drummer'),
              (3, 11, 'Vocals/Writer'),
              (3, 12, 'Vocals/Writer'),
              (4, 13, 'Vocals'),
              (4, 14, 'Writer'),
              (5, 15, 'Vocals/Writer'),
              (5, 16, 'Guitarist'),
              (5, 17, 'Drummer'),
              (5, 18, 'Bassist'),
              (6, 19, 'Vocals'),
              (6, 20, 'Vocals'),
              (6, 21, 'Vocals'),
              (6, 22, 'Vocals'),
              (6, 23, 'Vocals'),
              (7, 24, 'Vocals'),
              (7, 25, 'Writer'),  
              (8, 26, 'Vocals/Writer'),
              (9, 27, 'Vocals/Writer'),
              (10, 28, 'Vocals'),
              (10, 29, 'Vocals'),
              (10, 30, 'Vocals'),
              (10, 31, 'Vocals'),
              (10, 32, 'Vocals'),
              (11, 33, 'Vocals/Writer/Producer'),
              (12, 28, 'Vocals/Writer'),
              (13, 6, 'Vocals/Writer/Producer'),
              (14, 34, 'Vocals/Writer/Producer'),
              (15, 35, 'Vocals'),
              (15, 36, 'Vocals/Writer'),
              (15, 37, 'Vocals/Writer'),
              (15, 38, 'Writer'),
              (16, 39, 'Vocals'),
              (16, 40, 'Producer'),
              (17, 41, 'Vocals/Guitarist'),
              (17, 42, 'Vocals/Bassist'),
              (17, 43, 'Vocals/Guitarist/Writter'),
              (17, 44, 'Vocals/Drummer'),
              (18, 45, 'Vocals/Writer'),
              (18, 46, 'Vocals'),
              (18, 47, 'Producer'),
              (19, 48, 'Vocals/Writer/Producer'),
              (19, 15, 'Vocals/Writer/Producer'),
              (19, 16, 'Guitarist/Writer/Producer'),
              (19, 17, 'Drummer/Writer/Producer'),
              (19, 18, 'Bassist/Writer/Producer'),
              (20, 49, 'Rapping'),
              (20, 50, 'Vocals/Writer'),
              (20, 51, 'Producer'),
              (21, 52, 'Vocals/Write/Producer'),
              (21, 53, 'Vocals/Write/Producer'),
              (21, 54, 'Vocals/Write/Producer'),
              (22, 55, 'Vocals'),
              (22, 56, 'Vocals'),  
              (22, 57, 'Writer/Producer'),
              (23, 50, 'Vocals/Writer'),
              (24, 45, 'Vocals/Writer'),
              (25, 11, 'Vocals/Writer'),
              (26, 59, 'Vocals/Writer'),
              (26, 60, 'Vocals/Writer'),
              (26, 61, 'Vocals/Writer'),
              (26, 62, 'Vocals/Writer'),
              (26, 63, 'Vocals/Writer'),
              (27, 1, 'Writer/Producer'),
              (27, 58, 'Vocals'),
              (28, 64, 'Vocals/Writer/Producer'),
              (28, 65, 'Co-writer'),
              (29, 64, 'Vocals/Writer/Producer'),
              (29, 65, 'Vocals'),
              (30, 66, 'Vocals/Writer'),
              (30, 67, 'Rapping');

INSERT INTO Queues (USID, KID, SID)
       VALUES   
              (1, 13, 8),
              (2, 15, 9),
              (3, 15, 9),
              (4, 24, 16),
              (5, 33, 21);

INSERT INTO PQueues (USID, KID, SID, Amount)
       VALUES   
              (6, 47, 30, 10.00),
              (7, 42, 27, 6.50),
              (8, 22, 15, 12.45),
              (9, 43, 28, 2.00),
              (10, 5, 3, 8.75);